### ISSUE TITLE
Possible refactoring

### ISSUE THREAD

**Issue by antoniods311** [EnricoEmanuele/Swatcher#13]
- Rename MediaSettingWriteCommand class in MediaSettingSetCommand. This class contains business logic for "set command". 
- Create a new class called MediaSettingWriteCommand that contains business logic for "write command".

**Comment by wilmerci** [comment]
@antoniods311 the rename of class is done with substitution of all reference to old class. Build of app is OK after the operation.
Internal refactoring of the class will be do with the next commit using always this issue #13
