### ISSUE TITLE
possible update on TC_FR-02 after implementation of Function/GUI

### ISSUE THREAD

**Issue by wilmerci** [EnricoEmanuele/Swatcher#3]
depending on the situation that we decide to use a toast/small pop-up or a dedicated frame to realize step 5 of FR-02 probably we have to modify step 5 in the test case TC_FR-02 with a new entry.

**Comment by wilmerci** [comment]
same situation there is in TC_FR-03 step 3 and 3a.

**Comment by antoniods311** [comment]
no update for step 5 in FR-02.

**Comment by wilmerci** [comment]
ok @antoniods311 we can close this issue.
